# Generated by Django 2.2.10 on 2020-02-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200205_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image222',
            new_name='image',
        ),
    ]
