# Generated by Django 2.2.10 on 2020-02-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200205_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='sumary',
            new_name='summary',
        ),
    ]
